### ISSUE TITLE
Blank MatchID Error

### ISSUE THREAD

**Issue by xlkiller** [salumguilherme/reportbot#5]
Hi, 

I have this error and after 45 secs ScriptTimeout

Uncaught Exception. Error: TypeError: Cannot read property 'matchid' of undefined

**Comment by xlkiller** [comment]
Fixed by modify

`if(typeof list.matches[0].matchid == 'undefined')`

to

`if(typeof list.matches[0] == 'undefined')`

**Comment by xlkiller** [comment]
`csgo.requestLiveGameForUser(csgo.ToAccountID(String(ReportingID)));`

```
if (list.matches && list.matches.length > 0) {
                    var matchIDobj = JSON.parse(JSON.stringify(list.matches[0], null, 2));
                    MatchID = new Long(matchIDobj.matchid.low, matchIDobj.matchid.high, matchIDobj.matchid.unsigned).toString();
					console.log('[MatchID]'.green.bold + MatchID);
                    
               } else {
                    console.log('[ERROR]'.red.bold+' That player is not InGame !');
					steam_client.disconnect();
					Process.exit();
					return;
               }
```

**Comment by salumguilherme** [comment]
Hey mate, apologie for the late reply. I havent played csgo in over 4 months and I'm pretty sure Valve now is catching up on report bots. I'm leaving this repository open just as reference for people who want to develop further.
